[package]
name = "spiral-matrix"
version = "1.0.0"
authors = ["João Nuno Matos <me@joaonmatos.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
